version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "MAINT"
    groups:
       pip-deps:
          patterns:
            - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "MAINT"
    groups:
       actions-deps:
          patterns:
            - "*"
